import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

/** Self-contained: serialized into a plugin loaded by OpenCode's compiled Bun executable. */
export function installOpenCodeCapture(proxyUrl: string): { dispose(): Promise<void> } {
  const original = globalThis.fetch;
  const proxy = new URL(proxyUrl);
  let active = true;
  const wrapped: typeof fetch = function (input, init) {
    if (!active) return original(input, init);
    let target: URL;
    try {
      target = new URL(input instanceof Request ? input.url : String(input));
    } catch {
      return original(input, init);
    }
    // Match only model endpoints. OAuth login/refresh and other ChatGPT traffic stay untouched.
    // Preserve the actual origin so a configured Orca gateway cannot receive a ChatGPT token.
    const modelEndpoint =
      (target.hostname === 'chatgpt.com' && target.pathname === '/backend-api/codex/responses') ||
      (target.hostname === 'api.openai.com' &&
        ['/v1/responses', '/v1/chat/completions'].includes(target.pathname));
    if (
      !modelEndpoint ||
      target.protocol !== 'https:' ||
      target.port !== '' ||
      target.username !== '' ||
      target.password !== '' ||
      target.host === proxy.host
    ) {
      return original(input, init);
    }
    const moved =
      proxy.href.replace(/\/+$/, '') +
      '/forward/' +
      encodeURIComponent(target.origin) +
      target.pathname +
      target.search;
    // Preserve bodies, signals, headers and SDK fetch options. Never retry directly on failure:
    // a retry here could duplicate a model request or silently escape offline replay.
    return original(input instanceof Request ? new Request(moved, input) : moved, init);
  };
  // Bun adds helpers such as fetch.preconnect; other plugins may use them.
  Object.assign(wrapped, original);
  globalThis.fetch = wrapped;
  return {
    async dispose() {
      active = false;
      if (globalThis.fetch === wrapped) globalThis.fetch = original;
    },
  };
}

/** Local file URL works in both legacy and current OpenCode plugin loaders; no npm install. */
export async function writeOpenCodeCapturePlugin(
  runDir: string,
  proxyUrl: string,
): Promise<string> {
  const path = join(runDir, 'orca-opencode-capture.mjs');
  await mkdir(runDir, { recursive: true });
  await writeFile(
    path,
    `// Generated by OrcaReplay for this run. Contains no credentials.\n` +
      `${installOpenCodeCapture.toString()}\n` +
      `export default async function () { return installOpenCodeCapture(${JSON.stringify(proxyUrl)}); }\n`,
    { mode: 0o600 },
  );
  return pathToFileURL(path).href;
}
