import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { OPENCODE_API_BASES } from './opencode-api-bases.js';
import { collectOpenCodeApiBases, refreshOpenCodeApiBases } from './opencode-catalog.js';

interface OpenCodeModelInput {
  model?: { api?: { url?: string } };
  provider?: { options?: { baseURL?: string } };
}

/** Self-contained: serialized into a plugin loaded by OpenCode's compiled Bun executable. */
export function installOpenCodeCapture(
  proxyUrl: string,
  apiBases: string[] = [],
): {
  dispose(): Promise<void>;
  'chat.params'(input: OpenCodeModelInput): Promise<void>;
} {
  const original = globalThis.fetch;
  const proxy = new URL(proxyUrl);
  const bases = new Map<string, URL>();
  const addBase = (template: string | undefined) => {
    if (!template) return;
    const expanded = template.replace(
      /\$\{([^}]+)\}/g,
      (match, key: string) => process.env[key] ?? match,
    );
    // Unresolved templates must never become wildcard hosts or accidentally capture a login.
    if (expanded.includes('${')) return;
    try {
      const base = new URL(expanded);
      if (
        !['http:', 'https:'].includes(base.protocol) ||
        base.username ||
        base.password ||
        base.search ||
        base.hash ||
        base.origin === proxy.origin
      )
        return;
      base.pathname = base.pathname.replace(/\/+$/, '') || '/';
      bases.set(base.href, base);
    } catch {
      // A malformed catalog/config entry cannot redirect unrelated traffic.
    }
  };
  for (const base of apiBases) addBase(base);
  let active = true;
  const wrapped: typeof fetch = function (input, init) {
    if (!active) return original(input, init);
    let target: URL;
    try {
      target = new URL(input instanceof Request ? input.url : String(input));
    } catch {
      return original(input, init);
    }
    // Catalog paths are bases, not just hosts: /v1 must not match /v10 or another origin.
    // POST is the model transport supported by the proxy; leave SDK discovery GETs alone.
    const method = init?.method ?? (input instanceof Request ? input.method : 'GET');
    const catalogEndpoint =
      method.toUpperCase() === 'POST' &&
      [...bases.values()].some(
        (base) =>
          target.origin === base.origin &&
          (base.pathname === '/' ||
            target.pathname === base.pathname ||
            target.pathname.startsWith(base.pathname + '/')),
      );
    // OAuth login/refresh and other ChatGPT traffic stay untouched.
    // Preserve the actual origin so a configured Orca gateway cannot receive a ChatGPT token.
    const oauthEndpoint =
      (target.hostname === 'chatgpt.com' && target.pathname === '/backend-api/codex/responses') ||
      (target.hostname === 'api.openai.com' &&
        ['/v1/responses', '/v1/chat/completions'].includes(target.pathname));
    if (
      !(catalogEndpoint || (oauthEndpoint && target.protocol === 'https:' && target.port === '')) ||
      target.username !== '' ||
      target.password !== '' ||
      target.origin === proxy.origin
    ) {
      return original(input, init);
    }
    const moved =
      proxy.href.replace(/\/+$/, '') +
      '/forward/' +
      encodeURIComponent(target.origin) +
      target.pathname +
      target.search;
    // Preserve bodies, signals, headers and SDK fetch options. Never retry directly on failure:
    // a retry here could duplicate a model request or silently escape offline replay.
    return original(input instanceof Request ? new Request(moved, input) : moved, init);
  };
  // Bun adds helpers such as fetch.preconnect; other plugins may use them.
  Object.assign(wrapped, original);
  globalThis.fetch = wrapped;
  return {
    // Learn custom/current model bases without rewriting OpenCode's provider selection or URLs.
    async 'chat.params'(input) {
      if (!active) return;
      addBase(input.model?.api?.url);
      addBase(input.provider?.options?.baseURL);
    },
    async dispose() {
      active = false;
      if (globalThis.fetch === wrapped) globalThis.fetch = original;
    },
  };
}

/** Local file URL works in both legacy and current OpenCode plugin loaders; no npm install. */
export async function writeOpenCodeCapturePlugin(
  runDir: string,
  proxyUrl: string,
): Promise<string> {
  const path = join(runDir, 'orca-opencode-capture.mjs');
  await mkdir(runDir, { recursive: true });
  await writeFile(
    path,
    `// Generated by OrcaReplay for this run. Contains no credentials.\n` +
      `${installOpenCodeCapture.toString()}\n` +
      `${collectOpenCodeApiBases.toString()}\n` +
      `${refreshOpenCodeApiBases.toString()}\n` +
      `export default async function () {\n` +
      `  const bases = await refreshOpenCodeApiBases(${JSON.stringify(OPENCODE_API_BASES)}, !['1', 'true'].includes(process.env.OPENCODE_DISABLE_MODELS_FETCH));\n` +
      `  return installOpenCodeCapture(${JSON.stringify(proxyUrl)}, bases);\n` +
      `}\n`,
    { mode: 0o600 },
  );
  return pathToFileURL(path).href;
}
